// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BuyNow: typeof import('./resources/js/@core/components/BuyNow.vue')['default']
    CardStatisticsVertical: typeof import('./resources/js/@core/components/CardStatisticsVertical.vue')['default']
    ErrorHeader: typeof import('./resources/js/@core/components/ErrorHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./resources/js/@core/components/ThemeSwitcher.vue')['default']
  }
}
